### master node configurations
- hosts: Master
  become: 'yes'

  tasks:
    
    - name: Kubectl Install
      apt:
        name: kubectl
        state: present
        force: 'yes'
    
    - name: Start the cluster
      shell: kubeadm init --pod-network-cidr=192.168.0.0/16 >> cluster.txt
      register: result
      args:
        chdir: $HOME
        creates: cluster.txt
    
    - name: Sleep for 20 seconds
      wait_for:
        timeout: 20

    - name: Create .kube directory
      become: 'yes'
      become_user: ubuntu
      file:
        path: $HOME/.kube
        state: directory
        mode: 493
    
    - name: Check admin.conf file exists.
      stat:
        path: /etc/kubernetes/admin.conf
      register: k8s_conf
    
    - name: Copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: 'yes'
        owner: ubuntu
      when: k8s_conf.stat.exists
    
    - name: Install Pod network
      shell: sudo kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml >> pod_setup.txt
      args:
        chdir: $HOME
        creates: pod_setup.txt

    - name: Get worker node join command
      shell: kubeadm token create --print-join-command
      register: join_node_command
    
    - name: Copy worker node join command to local file
      local_action: copy content="{{ join_node_command.stdout_lines[0] }}" dest="./join_node_command"
