#Configure Worker Nodes
- hosts: Workers
  become: yes
  tasks:

    - name: Copy the worker join command to server location
      copy: src=join_node_command dest=/tmp/join_node_command.sh mode=0777

    - name: Join the worker node to cluster
      command: sh /tmp/join_node_command.sh